//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHM_Footies.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IHM_Footies.Ressources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🏠 Accueil.
        /// </summary>
        public static string Accueil {
            get {
                return ResourceManager.GetString("Accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un invité.
        /// </summary>
        public static string AjouterInvite {
            get {
                return ResourceManager.GetString("AjouterInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un menu.
        /// </summary>
        public static string AjouterMenu {
            get {
                return ResourceManager.GetString("AjouterMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un plat.
        /// </summary>
        public static string AjouterPlat {
            get {
                return ResourceManager.GetString("AjouterPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Anglais.
        /// </summary>
        public static string Anglais {
            get {
                return ResourceManager.GetString("Anglais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apéritif.
        /// </summary>
        public static string Aperitif {
            get {
                return ResourceManager.GetString("Aperitif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie*.
        /// </summary>
        public static string Categorie {
            get {
                return ResourceManager.GetString("Categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégories dans le menu.
        /// </summary>
        public static string CategoriesDansMenu {
            get {
                return ResourceManager.GetString("CategoriesDansMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dessert.
        /// </summary>
        public static string Dessert {
            get {
                return ResourceManager.GetString("Dessert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        public static string Enregistrer {
            get {
                return ResourceManager.GetString("Enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrée.
        /// </summary>
        public static string Entree {
            get {
                return ResourceManager.GetString("Entree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        public static string Francais {
            get {
                return ResourceManager.GetString("Francais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des invités.
        /// </summary>
        public static string GestionInvite {
            get {
                return ResourceManager.GetString("GestionInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des Menus.
        /// </summary>
        public static string GestionMenu {
            get {
                return ResourceManager.GetString("GestionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des menus.
        /// </summary>
        public static string GestionMenus {
            get {
                return ResourceManager.GetString("GestionMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des plats.
        /// </summary>
        public static string GestionPlats {
            get {
                return ResourceManager.GetString("GestionPlats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 👥 Groupes d&apos;invités.
        /// </summary>
        public static string GroupeInvite {
            get {
                return ResourceManager.GetString("GroupeInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🎟️ Invitations.
        /// </summary>
        public static string Invitations {
            get {
                return ResourceManager.GetString("Invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 👤 Invités.
        /// </summary>
        public static string Invites {
            get {
                return ResourceManager.GetString("Invites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue choisie :.
        /// </summary>
        public static string LangueChoisie {
            get {
                return ResourceManager.GetString("LangueChoisie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📋 Menus.
        /// </summary>
        public static string Menus {
            get {
                return ResourceManager.GetString("Menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un Invité.
        /// </summary>
        public static string ModifierInvite {
            get {
                return ResourceManager.GetString("ModifierInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un menu.
        /// </summary>
        public static string ModifierMenu {
            get {
                return ResourceManager.GetString("ModifierMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un plat.
        /// </summary>
        public static string ModifierPlat {
            get {
                return ResourceManager.GetString("ModifierPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom*.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du menu.
        /// </summary>
        public static string NomDuMenu {
            get {
                return ResourceManager.GetString("NomDuMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plat.
        /// </summary>
        public static string Plat {
            get {
                return ResourceManager.GetString("Plat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🍽️ Plats.
        /// </summary>
        public static string Plats {
            get {
                return ResourceManager.GetString("Plats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prenom*.
        /// </summary>
        public static string Prenom {
            get {
                return ResourceManager.GetString("Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réglages.
        /// </summary>
        public static string Reglages {
            get {
                return ResourceManager.GetString("Reglages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un invité.
        /// </summary>
        public static string SupprimerInvite {
            get {
                return ResourceManager.GetString("SupprimerInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un menu.
        /// </summary>
        public static string SupprimerMenu {
            get {
                return ResourceManager.GetString("SupprimerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un plat.
        /// </summary>
        public static string SupprimerPlat {
            get {
                return ResourceManager.GetString("SupprimerPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
    }
}
