//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHM_Footies.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IHM_Footies.Ressources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🏠 Accueil.
        /// </summary>
        public static string Accueil {
            get {
                return ResourceManager.GetString("Accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consulter les statistiques.
        /// </summary>
        public static string AfficherStats {
            get {
                return ResourceManager.GetString("AfficherStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un groupe d&apos;invité.
        /// </summary>
        public static string AjouterGroupeInvite {
            get {
                return ResourceManager.GetString("AjouterGroupeInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un invité.
        /// </summary>
        public static string AjouterInvite {
            get {
                return ResourceManager.GetString("AjouterInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un menu.
        /// </summary>
        public static string AjouterMenu {
            get {
                return ResourceManager.GetString("AjouterMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un plat.
        /// </summary>
        public static string AjouterPlat {
            get {
                return ResourceManager.GetString("AjouterPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une invitation.
        /// </summary>
        public static string ajoutinvit {
            get {
                return ResourceManager.GetString("ajoutinvit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allergène(s).
        /// </summary>
        public static string Allergene {
            get {
                return ResourceManager.GetString("Allergene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allergies.
        /// </summary>
        public static string Allergie {
            get {
                return ResourceManager.GetString("Allergie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⚠️ Allergie.
        /// </summary>
        public static string AllergieDanger {
            get {
                return ResourceManager.GetString("AllergieDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⚠️ Allergies Détectées.
        /// </summary>
        public static string AllergieDetect {
            get {
                return ResourceManager.GetString("AllergieDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allergies de l&apos;invité.
        /// </summary>
        public static string Allergies_invite {
            get {
                return ResourceManager.GetString("Allergies_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyse de l&apos;invitation.
        /// </summary>
        public static string AnalyseInvit {
            get {
                return ResourceManager.GetString("AnalyseInvit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Anglais.
        /// </summary>
        public static string Anglais {
            get {
                return ResourceManager.GetString("Anglais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apéritif.
        /// </summary>
        public static string Aperitif {
            get {
                return ResourceManager.GetString("Aperitif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour.
        /// </summary>
        public static string BoutonRetour {
            get {
                return ResourceManager.GetString("BoutonRetour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie*.
        /// </summary>
        public static string Categorie {
            get {
                return ResourceManager.GetString("Categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégories dans le menu.
        /// </summary>
        public static string CategoriesDansMenu {
            get {
                return ResourceManager.GetString("CategoriesDansMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaire (facultatif).
        /// </summary>
        public static string comfac {
            get {
                return ResourceManager.GetString("comfac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaires et impressions.
        /// </summary>
        public static string CommentairesImpression {
            get {
                return ResourceManager.GetString("CommentairesImpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string connexionvue {
            get {
                return ResourceManager.GetString("connexionvue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas encore de compte ? Créer un compte.
        /// </summary>
        public static string Creeruncompte {
            get {
                return ResourceManager.GetString("Creeruncompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CRÉER UN COMPTE.
        /// </summary>
        public static string Creeruncomptetitre {
            get {
                return ResourceManager.GetString("Creeruncomptetitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se déconnecter.
        /// </summary>
        public static string deconect {
            get {
                return ResourceManager.GetString("deconect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dessert.
        /// </summary>
        public static string Dessert {
            get {
                return ResourceManager.GetString("Dessert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 😞 Détesté.
        /// </summary>
        public static string DetesteDanger {
            get {
                return ResourceManager.GetString("DetesteDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2. Sélectionnez un plat.
        /// </summary>
        public static string deuxplat {
            get {
                return ResourceManager.GetString("deuxplat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à *Double-cliquez sur un élément pour afficher ses détails..
        /// </summary>
        public static string Double_Click {
            get {
                return ResourceManager.GetString("Double_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double-cliquez sur un invité pour voir ses informations..
        /// </summary>
        public static string Double_Click_invite {
            get {
                return ResourceManager.GetString("Double_Click_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double-cliquez sur un plat pour voir ses informations..
        /// </summary>
        public static string Double_Click_Plat {
            get {
                return ResourceManager.GetString("Double_Click_Plat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        public static string Enregistrer {
            get {
                return ResourceManager.GetString("Enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer la note.
        /// </summary>
        public static string enregistrernote {
            get {
                return ResourceManager.GetString("enregistrernote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;enregistrer.
        /// </summary>
        public static string enregistrerr {
            get {
                return ResourceManager.GetString("enregistrerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrée.
        /// </summary>
        public static string Entree {
            get {
                return ResourceManager.GetString("Entree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom :.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        public static string Francais {
            get {
                return ResourceManager.GetString("Francais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des invitations.
        /// </summary>
        public static string gestinvit {
            get {
                return ResourceManager.GetString("gestinvit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des groupes d’invités .
        /// </summary>
        public static string GestionGroupeInvite {
            get {
                return ResourceManager.GetString("GestionGroupeInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des invités.
        /// </summary>
        public static string GestionInvite {
            get {
                return ResourceManager.GetString("GestionInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des Menus.
        /// </summary>
        public static string GestionMenu {
            get {
                return ResourceManager.GetString("GestionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des menus.
        /// </summary>
        public static string GestionMenus {
            get {
                return ResourceManager.GetString("GestionMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gestion des plats.
        /// </summary>
        public static string GestionPlats {
            get {
                return ResourceManager.GetString("GestionPlats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Goûts.
        /// </summary>
        public static string Gout {
            get {
                return ResourceManager.GetString("Gout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 👥 Groupes d&apos;invités.
        /// </summary>
        public static string GroupeInvite {
            get {
                return ResourceManager.GetString("GroupeInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe d&apos;invités.
        /// </summary>
        public static string GwoupInvite {
            get {
                return ResourceManager.GetString("GwoupInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les informations de l&apos;invité.
        /// </summary>
        public static string InformationInvite {
            get {
                return ResourceManager.GetString("InformationInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos informations personnelles.
        /// </summary>
        public static string infosperso {
            get {
                return ResourceManager.GetString("infosperso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ingrédient(s).
        /// </summary>
        public static string Ingredient {
            get {
                return ResourceManager.GetString("Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🎟️ Invitations.
        /// </summary>
        public static string Invitations {
            get {
                return ResourceManager.GetString("Invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invités du Groupe.
        /// </summary>
        public static string InviteGroupe {
            get {
                return ResourceManager.GetString("InviteGroupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invites.
        /// </summary>
        public static string inviteinvit {
            get {
                return ResourceManager.GetString("inviteinvit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 👤 Invités.
        /// </summary>
        public static string Invites {
            get {
                return ResourceManager.GetString("Invites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue choisie :.
        /// </summary>
        public static string LangueChoisie {
            get {
                return ResourceManager.GetString("LangueChoisie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email :.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string mdp {
            get {
                return ResourceManager.GetString("mdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apéritif(s).
        /// </summary>
        public static string MenuAperitif {
            get {
                return ResourceManager.GetString("MenuAperitif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dessert(s).
        /// </summary>
        public static string MenuDessert {
            get {
                return ResourceManager.GetString("MenuDessert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrée(s).
        /// </summary>
        public static string MenuEntree {
            get {
                return ResourceManager.GetString("MenuEntree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plat(s).
        /// </summary>
        public static string MenuPlat {
            get {
                return ResourceManager.GetString("MenuPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📋 Menus.
        /// </summary>
        public static string Menus {
            get {
                return ResourceManager.GetString("Menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre invitation ne présente aucun conflit. Vous pouvez la valider sereinement..
        /// </summary>
        public static string Messageaucunconflit {
            get {
                return ResourceManager.GetString("Messageaucunconflit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🛈Sélectionnez les invités pour afficher leurs statistiques de fréquence de venue.
        /// </summary>
        public static string messageStats {
            get {
                return ResourceManager.GetString("messageStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifer un groupe d&apos;invité.
        /// </summary>
        public static string ModifierGroupeInvite {
            get {
                return ResourceManager.GetString("ModifierGroupeInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un Invité.
        /// </summary>
        public static string ModifierInvite {
            get {
                return ResourceManager.GetString("ModifierInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un menu.
        /// </summary>
        public static string ModifierMenu {
            get {
                return ResourceManager.GetString("ModifierMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un plat.
        /// </summary>
        public static string ModifierPlat {
            get {
                return ResourceManager.GetString("ModifierPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier une invitation.
        /// </summary>
        public static string modifinvit {
            get {
                return ResourceManager.GetString("modifinvit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mon Profil.
        /// </summary>
        public static string Monprofil {
            get {
                return ResourceManager.GetString("Monprofil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom :.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  repas au total.
        /// </summary>
        public static string NbFoisInvite {
            get {
                return ResourceManager.GetString("NbFoisInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✅ Aucun avertissement.
        /// </summary>
        public static string NoAvertissement {
            get {
                return ResourceManager.GetString("NoAvertissement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revenir sur mes choix.
        /// </summary>
        public static string NoChoix {
            get {
                return ResourceManager.GetString("NoChoix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom*.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du menu.
        /// </summary>
        public static string NomDuMenu {
            get {
                return ResourceManager.GetString("NomDuMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notation des plats.
        /// </summary>
        public static string Noteplat {
            get {
                return ResourceManager.GetString("Noteplat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Noter des plats.
        /// </summary>
        public static string noterplat {
            get {
                return ResourceManager.GetString("noterplat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plat.
        /// </summary>
        public static string Plat {
            get {
                return ResourceManager.GetString("Plat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plats détestés.
        /// </summary>
        public static string Plat_deteste {
            get {
                return ResourceManager.GetString("Plat_deteste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plat préféré de l&apos;invité.
        /// </summary>
        public static string Plat_prefere_invite {
            get {
                return ResourceManager.GetString("Plat_prefere_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 😞 Plats Détestés.
        /// </summary>
        public static string PlatDest {
            get {
                return ResourceManager.GetString("PlatDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plat favori.
        /// </summary>
        public static string PlatFavori {
            get {
                return ResourceManager.GetString("PlatFavori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plats.
        /// </summary>
        public static string platinvit {
            get {
                return ResourceManager.GetString("platinvit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 😊 Plats Préférés.
        /// </summary>
        public static string PlatPref {
            get {
                return ResourceManager.GetString("PlatPref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🍽️ Plats.
        /// </summary>
        public static string Plats {
            get {
                return ResourceManager.GetString("Plats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plats détestés par l&apos;invité.
        /// </summary>
        public static string Plats_detestes_invite {
            get {
                return ResourceManager.GetString("Plats_detestes_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plats préférés.
        /// </summary>
        public static string Plats_preferes {
            get {
                return ResourceManager.GetString("Plats_preferes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 😊 Préféré.
        /// </summary>
        public static string PrefereDanger {
            get {
                return ResourceManager.GetString("PrefereDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prenom*.
        /// </summary>
        public static string Prenom {
            get {
                return ResourceManager.GetString("Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pseudo.
        /// </summary>
        public static string pseudo {
            get {
                return ResourceManager.GetString("pseudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pseudo :.
        /// </summary>
        public static string pseudopur {
            get {
                return ResourceManager.GetString("pseudopur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher....
        /// </summary>
        public static string rechercher {
            get {
                return ResourceManager.GetString("rechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réglages.
        /// </summary>
        public static string Reglages {
            get {
                return ResourceManager.GetString("Reglages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 💬 Remarques.
        /// </summary>
        public static string Remarque {
            get {
                return ResourceManager.GetString("Remarque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la connexion.
        /// </summary>
        public static string Retouralaco {
            get {
                return ResourceManager.GetString("Retouralaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retours et Commentaires.
        /// </summary>
        public static string RetoursCommentaires {
            get {
                return ResourceManager.GetString("RetoursCommentaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🛈Sélectionnez les invités pour afficher leurs statistiques de fréquence de venue.
        /// </summary>
        public static string Se {
            get {
                return ResourceManager.GetString("Se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner tout.
        /// </summary>
        public static string selecttout {
            get {
                return ResourceManager.GetString("selecttout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📊 Statistiques.
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statistiques des invités.
        /// </summary>
        public static string StatsPage {
            get {
                return ResourceManager.GetString("StatsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page suivante.
        /// </summary>
        public static string suivante {
            get {
                return ResourceManager.GetString("suivante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un groupe d&apos;invité.
        /// </summary>
        public static string SupprimerGroupeInvite {
            get {
                return ResourceManager.GetString("SupprimerGroupeInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un invité.
        /// </summary>
        public static string SupprimerInvite {
            get {
                return ResourceManager.GetString("SupprimerInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un menu.
        /// </summary>
        public static string SupprimerMenu {
            get {
                return ResourceManager.GetString("SupprimerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un plat.
        /// </summary>
        public static string SupprimerPlat {
            get {
                return ResourceManager.GetString("SupprimerPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer une invitation.
        /// </summary>
        public static string supprinvit {
            get {
                return ResourceManager.GetString("supprinvit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 📈 Tableau de Bord.
        /// </summary>
        public static string TableaudeBord {
            get {
                return ResourceManager.GetString("TableaudeBord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Téléphone :.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3. Note attribuée (1-10).
        /// </summary>
        public static string troisnote {
            get {
                return ResourceManager.GetString("troisnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1. Sélectionnez un invité.
        /// </summary>
        public static string uninvit {
            get {
                return ResourceManager.GetString("uninvit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider l&apos;invitation.
        /// </summary>
        public static string ValideInvit {
            get {
                return ResourceManager.GetString("ValideInvit", resourceCulture);
            }
        }
    }
}
